[build-system]
requires = [
  "setuptools>=69",
  "wheel",
]
build-backend = "setuptools.build_meta"


[project]
name = "orbit-framework-core"
version = "0.2.0"
description = "Core framework runtime for Orbit"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }

authors = [
  { name = "Pranav Manglik" }
]

keywords = [
  "orbit",
  "framework",
  "runtime",
  "backend",
]

classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

dependencies = [
  "orbit-framework-types>=0.2.0",
  "typing-extensions>=4.12.0",
]


[tool.setuptools.packages.find]
include = ["orbit_core*"]