[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "orbit-framework-core"
version = "0.1.2"
description = "Core routing and dependency injection system for Orbit"
readme = "README.md"
requires-python = ">=3.11"

authors = [
    { name = "Pranav Manglik" }
]

license = { text = "MIT" }

dependencies = [
    "orbit-framework-types>=0.1.0"
]

keywords = ["orbit", "core", "di", "routing"]

classifiers = [
    "Development Status :: 3 - Alpha",

    "Intended Audience :: Developers",

    "License :: OSI Approved :: MIT License",

    "Operating System :: OS Independent",

    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",

    "Topic :: Software Development :: Libraries",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["orbit_core*"]


[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "ruff"
]
